# Generated by Django 5.0.4 on 2024-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_remove_post_file_post_image_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
